# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('ename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=50)),
            ],
        ),
    ]
